### ISSUE TITLE
 Congratulations for your CMS!

### ISSUE THREAD

**Issue by mrreaper47** [Markuu/WoW-CMS#1]
I am making my own private WoW server and trying to find a new and fresh CMS. I finally found your diamond in the rough.  

I think you're on the right track; but don't stop at the aesthetic/visual part and keep improving the functionalities.

If you need anything to keep your CMS growing, don't hesitate to contact me.

Sorry for my rustic English =)

**Comment by Markuu** [comment]
Thank you very much for your opinion, you don't even know how you motivated me, finally someone got interested in my project. This is a huge milestone for me. ^^
Anyway, thanks for the advice, I'm going to focus more on improving the code probably this weekend and adding some features.
If I need help, I will contact you for sure. :)
